import {
    BronzeArmorItem,
    ChainArmorItem,
    CoalItem,
    CobblestoneItem,
    CopperArmorItem,
    CopperIngotItem,
    CopperOreItem,
    CopperToolSetItem,
    IronArmorItem,
    IronIngotItem,
    IronOreItem,
    IronToolSetItem,
    LeatherClothesItem,
    LoadItem,
    LogItem,
    PlanksItem,
    RawBoarItem,
    RawRabbitItem,
    StickItem,
    StoneItem,
    StoneToolSetItem,
    StrawItem,
    WolfTalismanItem,
    WolfToothItem,
    WoolToolSetItem,
} from "@/assets/items"

// Define all items in the export object
export const itemComponent = {
    LOG: <LogItem />,
    STRAW: <StrawItem />,
    WOLF_TOOTH: <WolfToothItem />,
    RAW_RABBIT: <RawRabbitItem />,
    RAW_BOAR: <RawBoarItem />,
    COBBLESTONE: <CobblestoneItem />,
    COAL: <CoalItem />,
    COPPER_ORE: <CopperOreItem />,
    IRON_ORE: <IronOreItem />,
    LEATHER_CLOTHES: <LeatherClothesItem />,
    CHAIN_ARMOR: <ChainArmorItem />,
    COPPER_ARMOR: <CopperArmorItem />,
    BRONZE_ARMOR: <BronzeArmorItem />,
    IRON_ARMOR: <IronArmorItem />,
    STONE: <StoneItem />,
    COPPER_INGOT: <CopperIngotItem />,
    IRON_INGOT: <IronIngotItem />,
    PLANKS: <PlanksItem />,
    STICK: <StickItem />,
    WOOL_TOOL_SET: <WoolToolSetItem />,
    STONE_TOOL_SET: <StoneToolSetItem />,
    COPPER_TOOL_SET: <CopperToolSetItem />,
    IRON_TOOL_SET: <IronToolSetItem />,
    LOAD: <LoadItem />,
    WOLF_TALISMAN: <WolfTalismanItem />,
}
